In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('raw_data.csv')

In [3]:
df.head()

,ExternalReference,Q112,Q11_1,Q11_2,Q11_3,Q12_1,Q12_2,Q12_3,Q12_4,Q12_5,...,Gender_5_TEXT,Age,Experience,Education,Education_7_TEXT,Ethnicity,Race,Race_6_TEXT,Q108,Q109
0,Faculty of Arts and Sciences,1,5,5,5,4,2,4,2,4,...,,,,,,,,,,
1,School of Business,1,4,4,2,4,2,2,2,4,...,,,,,,,,,,
2,School of Business,1,5,5,3,4,4,4,4,4,...,,,,,,,,,,
3,Faculty of Arts and Sciences,1,1,1,1,1,1,1,5,5,...,,,,6,,2,,,,
4,Faculty of Arts and Sciences,1,5,5,2,1,3,4,4,4,...,,,15,6,,1,,,1,1

In [4]:
df.shape

(178, 88)

In [5]:
# Remove unnecessary columns
df.drop(columns=[
    "Q12_6reverse",
    "Q21_9reverse",
    "Q23_1reverse",
    "Q23_6reverse",
    "Gender_5_TEXT",
    "Q112"
], inplace=True)

In [6]:
df.shape

(178, 82)

In [7]:
df.rename(columns={

    # General Information
    "ExternalReference": "academic_unit",
    "Q112": "informed_consent",

    # Q1-1: GenAI Familiarity
    "Q11_1": "genai_familiarity",
    "Q11_2": "llm_familiarity",
    "Q11_3": "prompt_engineering_familiarity",

    # Q1-2: GenAI Training and Readiness
    "Q12_1": "adequate_genai_training",
    "Q12_2": "need_more_genai_training",
    "Q12_3": "understand_genai_classroom_use",
    "Q12_4": "students_need_more_genai_training",
    "Q12_5": "university_genai_discussion_channels",
    "Q12_6": "genai_training_unnecessary",
    "Q12_6reverse": "genai_training_unnecessary_reversed",

    # Q1-3: GenAI Tools for Writing
    "Q13": "genai_writing_tools",
    "Q13_6_TEXT": "other_genai_writing_tools",

    # Q1-4: GenAI Tools for Programming
    "Q14": "genai_programming_tools",
    "Q14_5_TEXT": "other_genai_programming_tools",

    # Q1-5: GenAI Tools for Audio-Visual Generation
    "Q15": "genai_audio_visual_tools",
    "Q15_8_TEXT": "other_genai_audio_visual_tools",

    # Q1-6: GenAI Instructional Tasks
    "Q16_1": "genai_content_generation",
    "Q16_2": "genai_text_summarization",
    "Q16_3": "genai_language_translation",
    "Q16_4": "genai_teaching_customer_service",
    "Q16_5": "genai_data_analysis_visualization",
    "Q16_6": "genai_programming_code_generation",
    "Q16_7": "genai_educational_support",
    "Q16_8": "genai_assignment_activities",
    "Q16_9": "genai_student_research_projects",

    # Q1-7: Other Instructional Uses
    "Q17": "other_genai_instructional_uses",

    # Q1-8: Current and Future Teaching Practices
    "Q18_1": "genai_syllabus_statement",
    "Q18_2": "genai_principles_discussion",
    "Q18_3": "genai_strengths_weaknesses",
    "Q18_4": "genai_ethics_discussion",
    "Q18_5": "genai_classroom_problem_solving",
    "Q18_6": "genai_homework_use",
    "Q18_7": "genai_exam_use",
    "Q18_8": "genai_critical_evaluation",
    "Q18_9": "genai_assignment_development",
    "Q18_10": "genai_standalone_rubric_feedback",
    "Q18_11": "genai_combined_feedback",
    "Q18_12": "other_genai_teaching_practices",
    "Q18_12_TEXT": "other_genai_teaching_practices_text",

    # Q1-9: GenAI Payment Status
    "Q19": "genai_payment_status",

    # Q1-10: Paid GenAI Services
    "Q110": "paid_genai_services",

    # Q2-1: Perceptions of GenAI
    "Q21_1": "genai_instructional_effectiveness",
    "Q21_2": "genai_instructor_efficiency",
    "Q21_3": "genai_personalized_learning",
    "Q21_4": "genai_curriculum_redesign",
    "Q21_5": "genai_future_job_impact",
    "Q21_6": "teaching_change_due_to_student_ai_use",
    "Q21_7": "teaching_change_for_better_outcomes",
    "Q21_8": "excitement_about_genai_integration",
    "Q21_9": "resistance_to_teaching_change",
    "Q21_9reverse": "resistance_to_teaching_change_reversed",

    # Q2-2: GenAI Risks and Ethical Concerns
    "Q22_1": "genai_student_learning_threat",
    "Q22_2": "genai_assignment_integrity_threat",
    "Q22_3": "genai_assessment_integrity_threat",
    "Q22_4": "genai_student_mental_health_threat",
    "Q22_5": "genai_misinformation_risk",
    "Q22_6": "genai_content_accuracy_concern",
    "Q22_7": "genai_prompt_bias_awareness",
    "Q22_8": "genai_prompt_ethical_considerations",
    "Q22_9": "genai_harmful_output_recognition",

    # Q2-3: Prompt Modification Ability
    "Q23": "genai_prompt_bias_mitigation_ability",

    # Q2-3: Student Cognitive Skills
    "Q23_1": "genai_problem_solving_improvement",
    "Q23_1reverse": "genai_problem_solving_improvement_reversed",
    "Q23_2": "genai_student_creativity_reduction",
    "Q23_3": "genai_independent_thinking_reduction",
    "Q23_4": "genai_deep_analysis_reduction",
    "Q23_5": "genai_student_skill_degradation",
    "Q23_6": "genai_student_reliability_doubts",
    "Q23_6reverse": "genai_student_reliability_doubts_reversed",
    "Q23_7": "genai_prompt_complexity",
    "Q23_8": "genai_prompt_time_consumption",

    # Q3: GenAI Teaching Experiences
    "Q31": "positive_genai_teaching_experience",
    "Q34": "negative_genai_teaching_experience",
    "Q37": "major_genai_teaching_concerns",

    # Section 4: Demographics
    "Gender": "instructor_gender",
    "Gender_5_TEXT": "gender_self_description",
    "Age": "instructor_age",
    "Experience": "years_of_teaching_experience",
    "Education": "highest_education_level",
    "Education_7_TEXT": "other_education_description",
    "Ethnicity": "hispanic_latino_ethnicity",
    "Race": "instructor_race",
    "Race_6_TEXT": "other_race_description",
    "Q108": "undergraduate_graduate_teaching",
    "Q109": "residential_online_teaching"

}, inplace=True)

In [8]:
df.head()

,academic_unit,genai_familiarity,llm_familiarity,prompt_engineering_familiarity,adequate_genai_training,need_more_genai_training,understand_genai_classroom_use,students_need_more_genai_training,university_genai_discussion_channels,genai_training_unnecessary,...,instructor_gender,instructor_age,years_of_teaching_experience,highest_education_level,other_education_description,hispanic_latino_ethnicity,instructor_race,other_race_description,undergraduate_graduate_teaching,residential_online_teaching
0,Faculty of Arts and Sciences,5,5,5,4,2,4,2,4,3,...,,,,,,,,,,
1,School of Business,4,4,2,4,2,2,2,4,2,...,2,,,,,,,,,
2,School of Business,5,5,3,4,4,4,4,4,4,...,,,,,,,,,,
3,Faculty of Arts and Sciences,1,1,1,1,1,1,5,5,1,...,2,,,6,,2,,,,
4,Faculty of Arts and Sciences,5,5,2,1,3,4,4,4,1,...,2,,15,6,,1,,,1,1

In [ ]:
df.shape
df.columns.tolist()

(178, 82)
['academic_unit', 'genai_familiarity', 'llm_familiarity', 'prompt_engineering_familiarity', 'adequate_genai_training', 'need_more_genai_training', 'understand_genai_classroom_use', 'students_need_more_genai_training', 'university_genai_discussion_channels', 'genai_training_unnecessary', 'genai_writing_tools', 'other_genai_writing_tools', 'genai_programming_tools', 'other_genai_programming_tools', 'genai_audio_visual_tools', 'other_genai_audio_visual_tools', 'genai_content_generation', 'genai_text_summarization', 'genai_language_translation', 'genai_teaching_customer_service', 'genai_data_analysis_visualization', 'genai_programming_code_generation', 'genai_educational_support', 'genai_assignment_activities', 'genai_student_research_projects', 'other_genai_instructional_uses', 'genai_syllabus_statement', 'genai_principles_discussion', 'genai_strengths_weaknesses', 'genai_ethics_discussion', 'genai_classroom_problem_solving', 'genai_homework_use', 'genai_exam_use', 'genai_critical_evaluation', 'genai_assignment_development', 'genai_standalone_rubric_feedback', 'genai_combined_feedback', 'other_genai_teaching_practices', 'other_genai_teaching_practices_text', 'genai_payment_status', 'paid_genai_services', 'genai_instructional_effectiveness', 'genai_instructor_efficiency', 'genai_personalized_learning', 'genai_curriculum_redesign', 'genai_future_job_impact', 'teaching_change_due_to_student_ai_use', 'teaching_change_for_better_outcomes', 'excitement_about_genai_integration', 'resistance_to_teaching_change', 'genai_student_learning_threat', 'genai_assignment_integrity_threat', 'genai_assessment_integrity_threat', 'genai_student_mental_health_threat', 'genai_misinformation_risk', 'genai_content_accuracy_concern', 'genai_prompt_bias_awareness', 'genai_prompt_ethical_considerations', 'genai_harmful_output_recognition', 'genai_prompt_bias_mitigation_ability', 'genai_problem_solving_improvement', 'genai_student_creativity_reduction', 'genai_independent_thinking_reduction', 'genai_deep_analysis_reduction', 'genai_student_skill_degradation', 'genai_student_reliability_doubts', 'genai_prompt_complexity', 'genai_prompt_time_consumption', 'positive_genai_teaching_experience', 'negative_genai_teaching_experience', 'major_genai_teaching_concerns', 'concern_categories', 'instructor_gender', 'instructor_age', 'years_of_teaching_experience', 'highest_education_level', 'other_education_description', 'hispanic_latino_ethnicity', 'instructor_race', 'other_race_description', 'undergraduate_graduate_teaching', 'residential_online_teaching']

In [10]:
missing = df.isnull().sum()
missing[missing != 0]

positive_genai_teaching_experience    13
negative_genai_teaching_experience    14
major_genai_teaching_concerns          4
concern_categories                    51
dtype: int64

In [11]:
df["academic_unit"] = (
    df["academic_unit"].str.strip().replace({
        "Faculty of Arts and Sciences": "Arts and Sciences",
        "School of Business": "Business",
        "School of Education": "Education",
        "School of Law": "Law",
        "School of Marine Science": "Marine Science",
        "": "Not reported",
        "-": "Not reported"
    }).fillna("Not reported")
)

In [12]:
df["academic_unit"].value_counts()

academic_unit
Arts and Sciences    114
Business              24
Education             13
Law                   12
Marine Science         8
Not reported           7
Name: count, dtype: int64

In [13]:
for col in df.columns:
    try:
        df[col] = df[col].str.strip()
        df[col] = df[col].replace("", pd.NA)
        df[col] = pd.to_numeric(df[col])
    except (ValueError, TypeError, AttributeError):
        pass

In [14]:
familiarity_labels = {
    1: "Not at all familiar",
    2: "Somewhat unfamiliar",
    3: "Neutral",
    4: "Somewhat familiar",
    5: "Very familiar"
}

In [15]:
familiarity_columns = [
    "genai_familiarity",
    "llm_familiarity",
    "prompt_engineering_familiarity"
]

In [16]:
for col in familiarity_columns:
    df[col] = df[col].replace(familiarity_labels)

In [17]:
df[familiarity_columns].head()

     genai_familiarity      llm_familiarity prompt_engineering_familiarity
0        Very familiar        Very familiar                  Very familiar
1    Somewhat familiar    Somewhat familiar            Somewhat unfamiliar
2        Very familiar        Very familiar                        Neutral
3  Not at all familiar  Not at all familiar            Not at all familiar
4        Very familiar        Very familiar            Somewhat unfamiliar

In [18]:
agreement_labels = {
    1: "Strongly disagree",
    2: "Disagree",
    3: "Neutral",
    4: "Agree",
    5: "Strongly agree"
}

In [19]:
agreement_columns = [
    "adequate_genai_training",
    "need_more_genai_training",
    "understand_genai_classroom_use",
    "students_need_more_genai_training",
    "university_genai_discussion_channels",
    "genai_training_unnecessary"
]

In [20]:
for col in agreement_columns:
    df[col] = df[col].replace(agreement_labels)

In [21]:
df[agreement_columns].head()

,adequate_genai_training,need_more_genai_training,understand_genai_classroom_use,students_need_more_genai_training,university_genai_discussion_channels,genai_training_unnecessary
0,Agree,Disagree,Agree,Disagree,Agree,Neutral
1,Agree,Disagree,Disagree,Disagree,Agree,Disagree
2,Agree,Agree,Agree,Agree,Agree,Agree
3,Strongly disagree,Strongly disagree,Strongly disagree,Strongly agree,Strongly agree,Strongly disagree
4,Strongly disagree,Neutral,Agree,Agree,Agree,Strongly disagree

In [22]:
writing_labels = {
    "1": "ChatGPT",
    "2": "Google Bard",
    "3": "Claude",
    "4": "Microsoft Bing AI",
    "5": "GrammarlyGo",
    "6": "Others",
    "7": "Never used any"
}

def convert_writing(value):
    if pd.isna(value):
        return value

    codes = str(value).split(",")
    names = []

    for code in codes:
        code = code.strip()
        names.append(writing_labels.get(code, code))

    return ", ".join(names)

df["genai_writing_tools"] = df["genai_writing_tools"].apply(convert_writing)

In [23]:
def clean_writing_tool(value):
    if pd.isna(value) or str(value).strip() == "":
        return pd.NA

    value = " ".join(str(value).split()).lower()

    if value.startswith("grammarly"):
        return "Grammarly"

    tool_names = {
        "quillbot": "QuillBot",
        "perplexity": "Perplexity",
        "google translate": "Google Translate",
        "github copilot": "GitHub Copilot",
        "microsoft word's native editor suggestions": "Microsoft Word Editor Suggestions",
        "dall-e 2": "DALL·E 2",
        "lexis+ ai": "Lexis+ AI"
    }

    return tool_names.get(value, "Others")


df["other_genai_writing_tools"] = df["other_genai_writing_tools"].apply(clean_writing_tool)

In [24]:
for i in df.index:
    main = df.loc[i, "genai_writing_tools"]
    other = df.loc[i, "other_genai_writing_tools"]

    if pd.isna(other):
        continue

    if pd.isna(main):
        df.loc[i, "genai_writing_tools"] = other

    elif "Others" in main:
        df.loc[i, "genai_writing_tools"] = main.replace("Others", other)

    elif other not in main.split(", "):
        df.loc[i, "genai_writing_tools"] = main + ", " + other

In [25]:
df.drop(columns="other_genai_writing_tools", inplace=True)

In [26]:
df["genai_writing_tools"].value_counts()

genai_writing_tools
Never used any                                                          69
ChatGPT                                                                 40
ChatGPT, GrammarlyGo                                                    16
ChatGPT, Google Bard                                                     9
ChatGPT, Microsoft Bing AI, GrammarlyGo                                  7
GrammarlyGo                                                              5
ChatGPT, Microsoft Bing AI                                               5
ChatGPT, Google Bard, Claude, Microsoft Bing AI                          3
ChatGPT, Google Bard, Microsoft Bing AI, GrammarlyGo                     3
ChatGPT, Google Bard, Microsoft Bing AI                                  3
ChatGPT, Google Bard, GrammarlyGo                                        2
ChatGPT, Microsoft Bing AI, QuillBot                                     1
ChatGPT, Microsoft Bing AI, Perplexity                                   1
GrammarlyGo, Google Translate                                            1
ChatGPT, Claude                                                          1
Others                                                                   1
ChatGPT, Claude, GrammarlyGo                                             1
ChatGPT, Google Bard, GrammarlyGo, GitHub Copilot                        1
ChatGPT, Others                                                          1
ChatGPT, Google Bard, Claude, Microsoft Bing AI, GrammarlyGo, Others     1
Grammarly                                                                1
ChatGPT, Google Bard, Claude, Microsoft Bing AI, GrammarlyGo             1
Microsoft Word Editor Suggestions                                        1
ChatGPT, DALL·E 2                                                        1
ChatGPT, Claude, Microsoft Bing AI, GrammarlyGo                          1
ChatGPT, Lexis+ AI                                                       1
ChatGPT, Perplexity                                                      1
Name: count, dtype: int64

In [27]:
programming_labels = {
    "1": "ChatGPT",
    "2": "Google Bard",
    "3": "Microsoft Bing AI",
    "4": "GitHub Copilot",
    "5": "Others",
    "6": "Never used any"
}

def convert_programming(value):
    if pd.isna(value):
        return value

    codes = str(value).split(",")
    names = []

    for code in codes:
        code = code.strip()
        names.append(programming_labels.get(code, code))

    return ", ".join(names)

df["genai_programming_tools"] = df["genai_programming_tools"].apply(convert_programming)

In [28]:
df["other_genai_programming_tools"] = df["other_genai_programming_tools"].str.strip()

df["other_genai_programming_tools"] = df["other_genai_programming_tools"].replace({
    "Custom LLMs (local)": "Others",
    "": pd.NA
})

In [29]:
for i in df.index:
    main = df.loc[i, "genai_programming_tools"]
    other = df.loc[i, "other_genai_programming_tools"]

    if pd.isna(other):
        continue

    if pd.isna(main):
        df.loc[i, "genai_programming_tools"] = other

    elif "Others" in main:
        df.loc[i, "genai_programming_tools"] = main.replace("Others", other)

    elif other not in main.split(", "):
        df.loc[i, "genai_programming_tools"] = main + ", " + other

In [30]:
df.drop(columns="other_genai_programming_tools", inplace=True)

In [31]:
df["genai_programming_tools"].value_counts()

genai_programming_tools
Never used any                                                     129
ChatGPT                                                             33
ChatGPT, GitHub Copilot                                              6
ChatGPT, Microsoft Bing AI                                           3
ChatGPT, Google Bard                                                 2
ChatGPT, Google Bard, GitHub Copilot                                 2
GitHub Copilot                                                       1
Others                                                               1
ChatGPT, Google Bard, Microsoft Bing AI, GitHub Copilot, Others      1
Name: count, dtype: int64

In [32]:
audio_visual_labels = {
    "1": "Stable Diffusion",
    "2": "Midjourney",
    "3": "Adobe Firefly",
    "4": "Make-A-Video",
    "5": "Microsoft Bing AI DALL-E",
    "6": "Photo_CreatE",
    "7": "Music LM",
    "8": "Others",
    "9": "Never used any"
}

def convert_audio_visual(value):
    if pd.isna(value):
        return value

    codes = str(value).split(",")
    names = []

    for code in codes:
        code = code.strip()
        names.append(audio_visual_labels.get(code, code))

    return ", ".join(names)

df["genai_audio_visual_tools"] = df["genai_audio_visual_tools"].apply(convert_audio_visual)

In [33]:
df["other_genai_audio_visual_tools"] = df["other_genai_audio_visual_tools"].str.strip()

df["other_genai_audio_visual_tools"] = df["other_genai_audio_visual_tools"].replace({
    "Pictory.AI": "Pictory AI",
    "WhatsApp sticker generation feature": "Others",
    "DALL-E 2": "DALL-E 2",
    "ChatGPT 4.0 uses DALL-E as well": "ChatGPT",
    "Gamma": "Gamma",
    "Canva": "Canva",
    "crayon.ai": "Crayon.ai",
    "": pd.NA
})

In [34]:
df.loc[
    df["other_genai_audio_visual_tools"].str.startswith("Note that DALL-E", na=False),
    "other_genai_audio_visual_tools"
] = "Others"

In [35]:
for i in df.index:
    main = df.loc[i, "genai_audio_visual_tools"]
    other = df.loc[i, "other_genai_audio_visual_tools"]

    if pd.isna(other):
        continue

    if pd.isna(main):
        df.loc[i, "genai_audio_visual_tools"] = other

    elif "Others" in main:
        df.loc[i, "genai_audio_visual_tools"] = main.replace("Others", other)

    elif other not in main.split(", "):
        df.loc[i, "genai_audio_visual_tools"] = main + ", " + other

In [36]:
df.drop(columns="other_genai_audio_visual_tools", inplace=True)

In [37]:
df["genai_audio_visual_tools"].value_counts()

genai_audio_visual_tools
Never used any                                                    127
Microsoft Bing AI DALL-E                                           17
Stable Diffusion, Midjourney                                        4
Stable Diffusion, Microsoft Bing AI DALL-E                          3
Stable Diffusion                                                    3
Midjourney, Microsoft Bing AI DALL-E                                2
Stable Diffusion, Midjourney, Microsoft Bing AI DALL-E              2
Midjourney, Adobe Firefly, Microsoft Bing AI DALL-E                 2
Midjourney                                                          2
Adobe Firefly, Microsoft Bing AI DALL-E                             2
Adobe Firefly                                                       2
Midjourney, Make-A-Video                                            1
Music LM                                                            1
Microsoft Bing AI DALL-E, Pictory AI                                1
Others                                                              1
Stable Diffusion, Midjourney, Microsoft Bing AI DALL-E, Others      1
DALL-E 2                                                            1
Microsoft Bing AI DALL-E, ChatGPT                                   1
Gamma                                                               1
Canva                                                               1
Crayon.ai                                                           1
Name: count, dtype: int64

In [38]:
frequency_labels = {
    1: "Never",
    2: "Rarely",
    3: "Sometimes",
    4: "Often",
    5: "Always"
}

In [39]:
frequency_columns = [
    "genai_content_generation",
    "genai_text_summarization",
    "genai_language_translation",
    "genai_teaching_customer_service",
    "genai_data_analysis_visualization",
    "genai_programming_code_generation",
    "genai_educational_support",
    "genai_assignment_activities",
    "genai_student_research_projects"
]

In [40]:
for col in frequency_columns:
    df[col] = df[col].replace(frequency_labels)

In [41]:
df[frequency_columns].head()

,genai_content_generation,genai_text_summarization,genai_language_translation,genai_teaching_customer_service,genai_data_analysis_visualization,genai_programming_code_generation,genai_educational_support,genai_assignment_activities,genai_student_research_projects
0,Rarely,Never,Never,Never,Never,Never,Never,Rarely,Rarely
1,Never,Never,Never,Never,Never,Never,Never,Never,Never
2,Sometimes,Never,Never,Never,Never,Never,Never,Never,Never
3,Never,Never,Never,Never,Never,Never,Never,Never,Never
4,Sometimes,Rarely,Often,Never,Sometimes,Never,Never,Never,Never

In [42]:
practice_labels = {
    1: "Current practice",
    2: "Intend to incorporate",
    3: "No plans to incorporate"
}

In [43]:
practice_columns = [
    "genai_syllabus_statement",
    "genai_principles_discussion",
    "genai_strengths_weaknesses",
    "genai_ethics_discussion",
    "genai_classroom_problem_solving",
    "genai_homework_use",
    "genai_exam_use",
    "genai_critical_evaluation",
    "genai_assignment_development",
    "genai_standalone_rubric_feedback",
    "genai_combined_feedback",
    "other_genai_teaching_practices"
]

In [44]:
for col in practice_columns:
    df[col] = df[col].replace(practice_labels)

In [45]:
df[practice_columns].head()

,genai_syllabus_statement,genai_principles_discussion,genai_strengths_weaknesses,genai_ethics_discussion,genai_classroom_problem_solving,genai_homework_use,genai_exam_use,genai_critical_evaluation,genai_assignment_development,genai_standalone_rubric_feedback,genai_combined_feedback,other_genai_teaching_practices
0,Current practice,Current practice,Current practice,Current practice,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,Current practice,No plans to incorporate,Current practice,No plans to incorporate
1,Current practice,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,NaN
2,Current practice,Current practice,Intend to incorporate,Current practice,Intend to incorporate,Intend to incorporate,Intend to incorporate,Intend to incorporate,Intend to incorporate,Intend to incorporate,Intend to incorporate,NaN
3,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate
4,Current practice,Current practice,Current practice,Current practice,Current practice,Current practice,No plans to incorporate,Intend to incorporate,No plans to incorporate,No plans to incorporate,No plans to incorporate,NaN

In [46]:
payment_labels = {
    1: "Paid in the past",
    2: "Currently paying",
    3: "Plan to pay",
    4: "Never paid / No plans",
    1.2: "Currently paying",
    2.3: "Currently paying",
    3.4: "Plan to pay"
}

df["genai_payment_status"] = df["genai_payment_status"].replace(payment_labels)

In [47]:
df["genai_payment_status"].value_counts(dropna=False)

genai_payment_status
Never paid / No plans    122
Currently paying          28
Plan to pay               20
NaN                        5
Paid in the past           3
Name: count, dtype: int64

In [48]:
tool_keywords = {
    "chatgpt": "ChatGPT",
    "chat gpt": "ChatGPT",
    "cgatgpt": "ChatGPT",
    "ghatgpt": "ChatGPT",
    "gpt 4": "ChatGPT",
    "grammarly": "Grammarly",
    "claude": "Claude",
    "pictory": "Pictory AI",
    "bard": "Google Bard",
    "dalle": "DALL-E 2",
    "scite": "Scite",
    "openai api": "OpenAI API",
    "python api": "OpenAI API"
}

In [49]:
def clean_paid_tools(value):
    if pd.isna(value) or str(value).strip() == "":
        return pd.NA

    text = str(value).lower()
    names = []

    for keyword, name in tool_keywords.items():
        if keyword in text and name not in names:
            names.append(name)

    if names:
        return ", ".join(names)
    else:
        return "Others"

In [50]:
df["paid_genai_services"] = df["paid_genai_services"].apply(clean_paid_tools)

In [51]:
df["paid_genai_services"].value_counts(dropna=False)

paid_genai_services
NaN                            152
ChatGPT                         16
Grammarly                        2
ChatGPT, OpenAI API              2
Others                           1
DALL-E 2                         1
ChatGPT, Claude, Pictory AI      1
ChatGPT, Google Bard             1
Scite                            1
ChatGPT, Grammarly               1
Name: count, dtype: int64

In [52]:
attitude_labels = {
    1: "Strongly disagree",
    2: "Somewhat disagree",
    3: "Neutral",
    4: "Somewhat agree",
    5: "Strongly agree",
    6: np.nan
}

In [53]:
attitude_columns = [
    "genai_instructional_effectiveness",
    "genai_instructor_efficiency",
    "genai_personalized_learning",
    "genai_curriculum_redesign",
    "genai_future_job_impact",
    "teaching_change_due_to_student_ai_use",
    "teaching_change_for_better_outcomes",
    "excitement_about_genai_integration",
    "resistance_to_teaching_change"
]

In [54]:
for col in attitude_columns:
    df[col] = df[col].replace(attitude_labels)

In [55]:
df[attitude_columns].head()

,genai_instructional_effectiveness,genai_instructor_efficiency,genai_personalized_learning,genai_curriculum_redesign,genai_future_job_impact,teaching_change_due_to_student_ai_use,teaching_change_for_better_outcomes,excitement_about_genai_integration,resistance_to_teaching_change
0,Somewhat agree,Somewhat agree,Somewhat disagree,Somewhat disagree,Somewhat agree,Somewhat agree,Neutral,Somewhat agree,Somewhat disagree
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral
3,Somewhat disagree,Somewhat disagree,Somewhat disagree,Somewhat disagree,Somewhat disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly agree
4,Somewhat agree,Somewhat agree,Neutral,Neutral,Neutral,Neutral,Somewhat agree,Somewhat agree,Strongly disagree

In [56]:
risk_columns = [
    "genai_student_learning_threat",
    "genai_assignment_integrity_threat",
    "genai_assessment_integrity_threat",
    "genai_student_mental_health_threat",
    "genai_misinformation_risk",
    "genai_content_accuracy_concern",
    "genai_prompt_bias_awareness",
    "genai_prompt_ethical_considerations",
    "genai_harmful_output_recognition"
]

In [57]:
for col in risk_columns:
    df[col] = df[col].replace(attitude_labels)

In [58]:
df[risk_columns].head()

,genai_student_learning_threat,genai_assignment_integrity_threat,genai_assessment_integrity_threat,genai_student_mental_health_threat,genai_misinformation_risk,genai_content_accuracy_concern,genai_prompt_bias_awareness,genai_prompt_ethical_considerations,genai_harmful_output_recognition
0,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat disagree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Somewhat disagree
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral
3,Strongly disagree,Strongly disagree,Somewhat agree,Neutral,Somewhat disagree,Somewhat agree,Somewhat agree,Neutral,Strongly disagree
4,Strongly disagree,Somewhat disagree,Somewhat disagree,Somewhat disagree,Somewhat agree,Somewhat agree,Somewhat agree,Neutral,Somewhat disagree

In [59]:
prompt_ability_labels = {
    1: "Not aware",
    2: "Cannot adjust",
    3: "Perhaps",
    4: "Know how"
}

df["genai_prompt_bias_mitigation_ability"] = pd.to_numeric(
    df["genai_prompt_bias_mitigation_ability"],
    errors="coerce"
)

df["genai_prompt_bias_mitigation_ability"] = df[
    "genai_prompt_bias_mitigation_ability"
].replace(prompt_ability_labels)

In [60]:
cognitive_columns = [
    "genai_problem_solving_improvement",
    "genai_student_creativity_reduction",
    "genai_independent_thinking_reduction",
    "genai_deep_analysis_reduction",
    "genai_student_skill_degradation",
    "genai_student_reliability_doubts",
    "genai_prompt_complexity",
    "genai_prompt_time_consumption"
]

In [61]:
for col in cognitive_columns:
    df[col] = df[col].replace(attitude_labels)

In [62]:
df[cognitive_columns].head()

,genai_problem_solving_improvement,genai_student_creativity_reduction,genai_independent_thinking_reduction,genai_deep_analysis_reduction,genai_student_skill_degradation,genai_student_reliability_doubts,genai_prompt_complexity,genai_prompt_time_consumption
0,Somewhat disagree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Somewhat agree,Somewhat disagree,Somewhat disagree
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral
3,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree
4,Neutral,Neutral,Somewhat agree,Somewhat agree,Neutral,Somewhat agree,Somewhat disagree,Somewhat disagree

In [63]:
gender_labels = {
    1: "Woman",
    2: "Man",
    3: "Non-binary",
    4: "Prefer not to say",
    5: "Prefer to self-describe"
}

df["instructor_gender"] = df["instructor_gender"].replace(gender_labels)

In [64]:
df["instructor_gender"].value_counts(dropna=False)

instructor_gender
Man                  93
Woman                68
Prefer not to say    10
NaN                   6
Non-binary            1
Name: count, dtype: int64

In [65]:
education_labels = {
    4: "Bachelor's degree",
    5: "Master's degree",
    6: "PhD/Doctoral degree",
    7: "Other Professional degree"
}

df["highest_education_level"] = df["highest_education_level"].replace(education_labels)

In [66]:
for i in df.index:
    if df.loc[i, "highest_education_level"] == "Other Professional degree":

        other = df.loc[i, "other_education_description"]

        if pd.notna(other) and str(other).strip():
            df.loc[i, "highest_education_level"] = str(other).strip()

In [67]:
df["highest_education_level"] = df["highest_education_level"].replace({
    "J.D.": "Juris Doctor (JD)",
    "JD": "Juris Doctor (JD)",
    "Juris Doctor": "Juris Doctor (JD)",
    "Ed.S (Educational Specialist - terminal degree)": "Education Specialist (Ed.S.)",
    "Four masters degrees/PhD ABD": "Master's degree"
})

In [68]:
df["highest_education_level"].value_counts(dropna=False)

highest_education_level
PhD/Doctoral degree             142
Master's degree                  23
NaN                               5
Juris Doctor (JD)                 5
Other Professional degree         2
Education Specialist (Ed.S.)      1
Name: count, dtype: int64

In [69]:
df.drop(columns="other_education_description", inplace=True)

In [70]:
ethnicity_labels = {
    1: "Yes",
    2: "No"
}

df["hispanic_latino_ethnicity"] = df["hispanic_latino_ethnicity"].replace(ethnicity_labels)

In [71]:
df["hispanic_latino_ethnicity"].value_counts(dropna=False)

hispanic_latino_ethnicity
No     156
Yes     13
NaN      9
Name: count, dtype: int64

In [72]:
race_labels = {
    1: "African American or Black",
    2: "American Indian or Alaskan Native",
    3: "Asian",
    4: "Native Hawaiian or Pacific Islander",
    5: "White",
    6: "Other",
    7: "Multi-racial",
    2.5: "Multi-racial",
    3.5: "Multi-racial"
}

df["instructor_race"] = df["instructor_race"].replace(race_labels)

In [73]:
def convert_race(value):
    if pd.isna(value) or str(value).strip() == "":
        return pd.NA

    codes = str(value).split(",")
    names = []

    for code in codes:
        code = code.strip()
        names.append(race_labels.get(code, code))

    return ", ".join(names)

df["instructor_race"] = df["instructor_race"].apply(convert_race)

In [74]:
df["instructor_race"].value_counts(dropna=False)

instructor_race
White                        132
Asian                         17
NaN                           13
Multi-racial                   8
African American or Black      5
Other                          3
Name: count, dtype: int64

In [75]:
teaching_level_labels = {
    1: "Undergraduate",
    2: "Graduate",
    3: "Both"
}

df["undergraduate_graduate_teaching"] = df["undergraduate_graduate_teaching"].replace(teaching_level_labels)

In [76]:
df["undergraduate_graduate_teaching"].value_counts(dropna=False)

undergraduate_graduate_teaching
Undergraduate    85
Both             52
Graduate         37
NaN               4
Name: count, dtype: int64

In [77]:
teaching_format_labels = {
    1: "Residential",
    2: "Online",
    3: "Both"
}

df["residential_online_teaching"] = df["residential_online_teaching"].replace(teaching_format_labels)

In [78]:
df["residential_online_teaching"].value_counts(dropna=False)

residential_online_teaching
Residential    145
NaN             23
Online          10
Name: count, dtype: int64

In [79]:
df.to_csv('cleaned_data.csv', index=False)